<?php
use App\country;
use App\Brand;
use App\city;
/* custom routes generated by CRUD */

Route::get('qr-code', function () 
{
	return QRCode::text('QR Code Generator for Laravel!')->png();    
});
Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

	Route::get('categories', ['as'=> 'categories.index', 'uses' => 'CategoriesController@index']);
	Route::post('categories', ['as'=> 'categories.daterange', 'uses' => 'CategoriesController@getdata']);
	Route::post('categories/store', ['as'=> 'categories.store', 'uses' => 'CategoriesController@store']);
	Route::get('categories/create', ['as'=> 'categories.create', 'uses' => 'CategoriesController@create']);
	Route::put('categories/{categories}', ['as'=> 'categories.update', 'uses' => 'CategoriesController@update']);
	Route::patch('categories/{categories}', ['as'=> 'categories.update', 'uses' => 'CategoriesController@update']);
	Route::get('categories/{id}/delete', array('as' => 'categories.delete', 'uses' => 'CategoriesController@getDelete'));
	Route::get('categories/{id}/confirm-delete', array('as' => 'categories.confirm-delete', 'uses' => 'CategoriesController@getModalDelete'));
	Route::get('categories/{categories}', ['as'=> 'categories.show', 'uses' => 'CategoriesController@show']);
	Route::get('categories/{categories}/edit', ['as'=> 'categories.edit', 'uses' => 'CategoriesController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

	Route::get('tests', ['as'=> 'tests.index', 'uses' => 'TestController@index']);
	Route::post('tests', ['as'=> 'tests.store', 'uses' => 'TestController@store']);
	Route::get('tests/create', ['as'=> 'tests.create', 'uses' => 'TestController@create']);
	Route::put('tests/{tests}', ['as'=> 'tests.update', 'uses' => 'TestController@update']);
	Route::patch('tests/{tests}', ['as'=> 'tests.update', 'uses' => 'TestController@update']);
	Route::get('tests/{id}/delete', array('as' => 'tests.delete', 'uses' => 'TestController@getDelete'));
	Route::get('tests/{id}/confirm-delete', array('as' => 'tests.confirm-delete', 'uses' => 'TestController@getModalDelete'));
	Route::get('tests/{tests}', ['as'=> 'tests.show', 'uses' => 'TestController@show']);
	Route::get('tests/{tests}/edit', ['as'=> 'tests.edit', 'uses' => 'TestController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

	Route::get('shops', ['as'=> 'stores.index', 'uses' => 'StoresController@index']);
	Route::get('shops/App_Shops', ['as'=> 'stores.app', 'uses' => 'StoresController@app_shop']);
	Route::post('shops', ['as'=> 'shops.daterange', 'uses' => 'StoresController@getdata']);
	Route::post('shops/app_shops', ['as'=> 'shops.appdaterange', 'uses' => 'StoresController@get_app_shop_data']);
	Route::post('shops/store', ['as'=> 'stores.store', 'uses' => 'StoresController@store']);
	Route::get('stores/create', ['as'=> 'stores.create', 'uses' => 'StoresController@create']);
	Route::put('stores/{stores}', ['as'=> 'stores.update', 'uses' => 'StoresController@update']);
	Route::patch('stores/{stores}', ['as'=> 'stores.update', 'uses' => 'StoresController@update']);
	Route::patch('stores/{stores}', ['as'=> 'stores.appupdate', 'uses' => 'StoresController@appupdate']);
	Route::get('stores/{id}/delete', array('as' => 'stores.delete', 'uses' => 'StoresController@getDelete'));
	Route::get('stores/{id}/confirm-delete', array('as' => 'stores.confirm-delete', 'uses' => 'StoresController@getModalDelete'));
	Route::get('stores/{stores}', ['as'=> 'stores.show', 'uses' => 'StoresController@show']);
	Route::get('stores/{stores}/edit', ['as'=> 'stores.edit', 'uses' => 'StoresController@edit']);
	Route::get('stores/{stores}/app_shop_edit', ['as'=> 'stores.appedit', 'uses' => 'StoresController@app_shop_edit']);
	Route::get('skutargets/create/{id?}', ['as'=> 'skutargets.create', 'uses' => 'SkutargetController@create']);


});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

	Route::get('tasks', ['as'=> 'tasks.index', 'uses' => 'TaskController@index']);
	Route::post('tasks/users', ['as'=> 'tasks.user', 'uses' => 'TaskController@usertasks']);
	Route::post('tasks/update', ['as'=> 'tasks.calendarupdated', 'uses' => 'TaskController@calendarupdated']);
	Route::get('tasks/users/{id}', ['as'=> 'tasks.userid', 'uses' => 'TaskController@usertasksbyId']);
	Route::post('tasks', ['as'=> 'tasks.daterange', 'uses' => 'TaskController@getdata']);
	Route::post('tasks/store', ['as'=> 'tasks.store', 'uses' => 'TaskController@store']);
	Route::get('tasks/store/{request}/{id}', ['as'=> 'tasks.ajaxstore', 'uses' => 'TaskController@ajaxstore']);
	Route::get('tasks/create/{employeeId}', ['as'=> 'tasks.create', 'uses' => 'TaskController@create']);
	Route::post('tasks/create/', ['as'=> 'tasks.create', 'uses' => 'TaskController@create']);
	Route::put('tasks/{tasks}', ['as'=> 'tasks.update', 'uses' => 'TaskController@update']);
	Route::patch('tasks/{tasks}', ['as'=> 'tasks.update', 'uses' => 'TaskController@update']);
	Route::get('tasks/{id}/delete', array('as' => 'tasks.delete', 'uses' => 'TaskController@getDelete'));
	Route::get('tasks/delete/{id}', array('as' => 'tasks.deleteviacalendar', 'uses' => 'TaskController@tasktDelete'));
	Route::get('tasks/{id}/confirm-delete', array('as' => 'tasks.confirm-delete', 'uses' => 'TaskController@getModalDelete'));
	Route::get('tasks/{tasks}', ['as'=> 'tasks.show', 'uses' => 'TaskController@show']);
	Route::get('tasks/{tasks}/edit', ['as'=> 'tasks.edit', 'uses' => 'TaskController@edit']);
	Route::get('tasks/edit/{tasks}', ['as'=> 'employeetasks.edit', 'uses' => 'TaskController@edit']);

});
Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {
	Route::get('table/{name}/{from}/{to}','FilterController@getdata');
});

Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {
	Route::get('interceptions', ['as'=> 'interceptions.index', 'uses' => 'InterceptionsController@index']);
	Route::post('interceptions', ['as'=> 'interceptions.daterange', 'uses' => 'InterceptionsController@getdata']);

});  
Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

	Route::get('brands', ['as'=> 'brands.index', 'uses' => 'BrandsController@index']);
	Route::post('brands', ['as'=> 'brands.daterange', 'uses' => 'BrandsController@getdata']);
	Route::post('brands/store', ['as'=> 'brands.store', 'uses' => 'BrandsController@store']);
	Route::get('brands/create', ['as'=> 'brands.create', 'uses' => 'BrandsController@create']);
	Route::get('brands/cities/{brand}', 'BrandsController@cities');
	Route::get('brands/demo', ['as'=> 'brands.demo', 'uses' => 'BrandsController@demo']);
	Route::put('brands/{brands}', ['as'=> 'brands.update', 'uses' => 'BrandsController@update']);
	Route::patch('brands/{brands}', ['as'=> 'brands.update', 'uses' => 'BrandsController@update']);
	Route::get('brands/{id}/delete', array('as' => 'brands.delete', 'uses' => 'BrandsController@getDelete'));
	Route::get('brands/{id}/confirm-delete', array('as' => 'brands.confirm-delete', 'uses' => 'BrandsController@getModalDelete'));
	Route::get('brands/{brands}', ['as'=> 'brands.show', 'uses' => 'BrandsController@show']);
	Route::get('brands/{brands}/edit', ['as'=> 'brands.edit', 'uses' => 'BrandsController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

	Route::get('assets', ['as'=> 'assets.index', 'uses' => 'AssetController@index']);
	Route::post('assets', ['as'=> 'assets.daterange', 'uses' => 'AssetController@getdata']);
	Route::post('assets/store', ['as'=> 'assets.store', 'uses' => 'AssetController@store']);
	Route::get('assets/create', ['as'=> 'assets.create', 'uses' => 'AssetController@create']);
	Route::put('assets/{assets}', ['as'=> 'assets.update', 'uses' => 'AssetController@update']);
	Route::patch('assets/{assets}', ['as'=> 'assets.update', 'uses' => 'AssetController@update']);
	Route::get('assets/{id}/delete', array('as' => 'assets.delete', 'uses' => 'AssetController@getDelete'));
	Route::get('assets/{id}/confirm-delete', array('as' => 'assets.confirm-delete', 'uses' => 'AssetController@getModalDelete'));
	Route::get('assets/{assets}', ['as'=> 'assets.show', 'uses' => 'AssetController@show']);
	Route::get('assets/{assets}/edit', ['as'=> 'assets.edit', 'uses' => 'AssetController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

	Route::get('sKUS', ['as'=> 'sKUS.index', 'uses' => 'SKUController@index']);
	Route::post('sKUS', ['as'=> 'sKUS.daterange', 'uses' => 'SKUController@getdata']);
	Route::post('sKUS/store', ['as'=> 'sKUS.store', 'uses' => 'SKUController@store']);
	Route::get('sKUS/create', ['as'=> 'sKUS.create', 'uses' => 'SKUController@create']);
	Route::put('sKUS/{sKUS}', ['as'=> 'sKUS.update', 'uses' => 'SKUController@update']);
	Route::patch('sKUS/{sKUS}', ['as'=> 'sKUS.update', 'uses' => 'SKUController@update']);
	Route::get('sKUS/{id}/delete', array('as' => 'sKUS.delete', 'uses' => 'SKUController@getDelete'));
	Route::get('sKUS/{id}/confirm-delete', array('as' => 'sKUS.confirm-delete', 'uses' => 'SKUController@getModalDelete'));
	Route::get('sKUS/{sKUS}', ['as'=> 'sKUS.show', 'uses' => 'SKUController@show']);
	Route::get('sKUS/{sKUS}/edit', ['as'=> 'sKUS.edit', 'uses' => 'SKUController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

	Route::get('employees', ['as'=> 'employees.index', 'uses' => 'EmployeeController@index']);
	Route::post('employees', ['as'=> 'employees.daterange', 'uses' => 'EmployeeController@getdata']);
	Route::post('employees/store', ['as'=> 'employees.store', 'uses' => 'EmployeeController@store']);
	Route::get('employees/create', ['as'=> 'employees.create', 'uses' => 'EmployeeController@create']);
	Route::put('employees/{employees}', ['as'=> 'employees.update', 'uses' => 'EmployeeController@update']);
	Route::patch('employees/{employees}', ['as'=> 'employees.update', 'uses' => 'EmployeeController@update']);
	Route::get('employees/{id}/delete', array('as' => 'employees.delete', 'uses' => 'EmployeeController@getDelete'));
	Route::get('employees/{id}/confirm-delete', array('as' => 'employees.confirm-delete', 'uses' => 'EmployeeController@getModalDelete'));
	Route::get('employees/{employees}', ['as'=> 'employees.show', 'uses' => 'EmployeeController@show']);
	Route::get('employees/{employees}/edit', ['as'=> 'employees.edit', 'uses' => 'EmployeeController@edit']);
	Route::get('employees/states/{id}','EmployeeController@states');
	Route::get('employees/countrystates/{id}','EmployeeController@countrystates');
	Route::get('employees/districts/{id}','EmployeeController@districts');
	Route::get('employees/BrandCities/{id}','EmployeeController@BrandCities');
	Route::get('employees/Brandstores/{id}/{brandId}','EmployeeController@Brandstores');
	Route::get('employees/Brandsupervisors/{id}','EmployeeController@Brandsupervisors');

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {


	Route::get('skutargets/{storeid?}', ['as'=> 'skutargets.index', 'uses' => 'SkutargetController@index']);
	Route::post('skutargets', ['as'=> 'skutargets.daterange', 'uses' => 'SkutargetController@getdata']);
	Route::post('skutargets/store', ['as'=> 'skutargets.store', 'uses' => 'SkutargetController@store']);
	Route::get('skutargets/create/{id?}', ['as'=> 'skutargets.create', 'uses' => 'SkutargetController@create']);
	Route::put('skutargets/{skutargets}', ['as'=> 'skutargets.update', 'uses' => 'SkutargetController@update']);
	Route::patch('skutargets/{skutargets}', ['as'=> 'skutargets.update', 'uses' => 'SkutargetController@update']);
	Route::get('skutargets/{id}/delete', array('as' => 'skutargets.delete', 'uses' => 'SkutargetController@getDelete'));
	Route::get('skutargets/{id}/confirm-delete', array('as' => 'skutargets.confirm-delete', 'uses' => 'SkutargetController@getModalDelete'));
	Route::get('skutargets/{skutargets}/edit', ['as'=> 'skutargets.edit', 'uses' => 'SkutargetController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

	Route::get('attendances', ['as'=> 'attendances.index', 'uses' => 'AttendanceController@index']);
	Route::post('attendances', ['as'=> 'attendances.store', 'uses' => 'AttendanceController@store']);
	Route::get('attendances/create', ['as'=> 'attendances.create', 'uses' => 'AttendanceController@create']);
	Route::put('attendances/{attendances}', ['as'=> 'attendances.update', 'uses' => 'AttendanceController@update']);
	Route::patch('attendances/{attendances}', ['as'=> 'attendances.update', 'uses' => 'AttendanceController@update']);
	Route::get('attendances/{id}/delete', array('as' => 'attendances.delete', 'uses' => 'AttendanceController@getDelete'));
	Route::get('attendances/{id}/confirm-delete', array('as' => 'attendances.confirm-delete', 'uses' => 'AttendanceController@getModalDelete'));
	Route::get('attendances/{attendances}', ['as'=> 'attendances.show', 'uses' => 'AttendanceController@show']);
	Route::get('attendances/{attendances}/edit', ['as'=> 'attendances.edit', 'uses' => 'AttendanceController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

	Route::get('eBStags', ['as'=> 'eBStags.index', 'uses' => 'EBStagController@index']);
	Route::post('eBStags', ['as'=> 'eBStags.store', 'uses' => 'EBStagController@store']);
	Route::get('eBStags/create', ['as'=> 'eBStags.create', 'uses' => 'EBStagController@create']);
	Route::put('eBStags/{eBStags}', ['as'=> 'eBStags.update', 'uses' => 'EBStagController@update']);
	Route::patch('eBStags/{eBStags}', ['as'=> 'eBStags.update', 'uses' => 'EBStagController@update']);
	Route::get('eBStags/{id}/delete', array('as' => 'eBStags.delete', 'uses' => 'EBStagController@getDelete'));
	Route::get('eBStags/{id}/confirm-delete', array('as' => 'eBStags.confirm-delete', 'uses' => 'EBStagController@getModalDelete'));
	Route::get('eBStags/{eBStags}', ['as'=> 'eBStags.show', 'uses' => 'EBStagController@show']);
	Route::get('eBStags/{eBStags}/edit', ['as'=> 'eBStags.edit', 'uses' => 'EBStagController@edit']);

});
Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {
	Route::get('getsale', ['as'=> 'reports.sale', 'uses' => 'ReportController@getsale']);
	Route::get('reports', ['as'=> 'reports.index', 'uses' => 'ReportController@index']);
	Route::get('reports/attendance', ['as'=> 'reports.attendance', 'uses' => 'ReportController@attendance']);
	Route::get('reports/daily_sale_report', ['as'=> 'reports.daily_sale_report', 'uses' => 'ReportController@daily_sale_report']);
	Route::post('reports/daily_sale_report', ['as'=> 'reports.daily_sale_report', 'uses' => 'ReportController@get_daily_sale_report']);
	Route::get('reports/attendance_report', ['as'=> 'reports.attendance_report', 'uses' => 'ReportController@attendance_report']);
	Route::post('reports/attendance_report', ['as'=> 'reports.get_attendance_report', 'uses' => 'ReportController@get_attendance_report']);
	Route::get('reports/maps', function(){
		return view('maps');
	});

	//developer irfan mumtaz
	Route::get('reports/brand-share', 'Admin\ReportController@brandShare')->name('brandShareIndex');
	Route::post('reports/brand-share-ajax', 'Admin\ReportController@brandShareAjax')->name('brandShareAjax');
	Route::get('reports/consumer-survery', 'Admin\ReportController@genderWise')->name('genderWise');
	Route::post('reports/consumer-survery-ajax', 'Admin\ReportController@genderWiseAjax')->name('genderWiseAjax');
	Route::get('/get-shops-by-brands/{id?}', 'Admin\ReportController@getShopsByBrands')->name('getShopsByBrands');
	Route::get('/reports/interception-report', 'Admin\ReportController@interception')->name('interception');
});
Route::get('clear', function () {
	
	/* php artisan migrate */
	Artisan::call('cache:clear');
	Artisan::call('config:cache');
	dd("Done");
});
